export const OBTENER_PRODUCTOS='OBTENER_PRODUCTOS';

//Carrito
export const AGREGAR_PRODUCTO_CARRITO='AGREGAR_PRODUCTO_CARRITO';

//usuarios
export const LOGIN_USUARIO='LOGIN_USUARIO';
export const LOGIN_USUARIO_ERROR='LOGIN_USUARIO_ERROR';
export const USUARIO_AUTENTICADO='USUARIO_AUTENTICADO'
