export const OBTENER_PRODUCTOS='OBTENER_PRODUCTOS';
export const ESTABLECER_IMAGEN='ESTABLECER_IMAGEN';

//Carrito
export const AGREGAR_PRODUCTO_CARRITO='AGREGAR_PRODUCTO_CARRITO';
export const AGREGAR_PRODUCTO_ERROR='AGREGAR_PRODUCTO_ERROR';
export const OBTENER_CARRITO='OBTENER_CARRITO';
export const AGREGADO_FALSE='AGREGADO_FALSE';
export const ESTABLECE_ORDEN='ESTABLECE_ORDEN';


//usuarios
export const REGISTRO_EXITOSO='REGISTRO_EXITOSO';
export const REGISTRO_ERROR='REGISTRO_ERROR'; 
export const LOGIN_EXITOSO='LOGIN_EXITOSO';
export const LOGIN_ERROR='LOGIN_ERROR';
export const USUARIO_AUTENTICADO='USUARIO_AUTENTICADO';
export const CERRAR_SESION='CERRAR_SESION';

//mensajes
export const OCULTAR_MENSAJE='OCULTAR_MENSAJE';
