export const OBTENER_PRODUCTOS='OBTENER_PRODUCTOS';

//Carrito
export const AGREGAR_PRODUCTO_CARRITO='AGREGAR_PRODUCTO_CARRITO';

//usuarios
export const CREAR_USUARIO='CREAR_USUARIO';
export const CREAR_USUARIO_ERROR='CREAR_USUARIO_ERROR'; 
export const LOGIN_USUARIO='LOGIN_USUARIO';
export const LOGIN_USUARIO_ERROR='LOGIN_USUARIO_ERROR';
export const USUARIO_AUTENTICADO='USUARIO_AUTENTICADO';

//mensajes

export const OCULTAR_MENSAJE='OCULTAR_MENSAJE';